### PR TITLE
Multiple controllers

### PR DESCRIPTION
**Pull request by mike0256**
Added in multiple distinct player controls. At the moment we support two players on the keyboard. Game controllers to follow.
Current controls:

Player 1:
Q Start (prints character state)
W Jump
E Dash
A Left
D Right
S Attack

Player 2:
O Start (prints character state)
P Jump
{ Dash
L Left
' Right
; Attack

### CODE REVIEW

**Comment by carterworks** [comment]
I think you forgot to commit some files. I don't see anything that uses the new PlayerController code

**Comment by mike0256** [comment]
@ThatCarterMcBride Nothing else needed to change. Since the PlayerController emits a signal (notifies its observers), all that needed to change was the inputs that it listens for, not the signals that it emits.

**Comment by carterworks** [comment]
Gotcha. Looks good then

**Review by carterworks — APPROVED** [review]
👍

**Pull request merged**
